name: ETL

on:
  schedule:
    - cron: '0 23 * * *' # Run daily at 11 pm
  push:
    branches: [ main ]
    paths:
      - 'data_upload/**' # Trigger only when changes occur in the data_upload folder or its subfolders

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("readr","RSQLite","stringr"))'
      - name: Execute R script
        run: |
          Rscript R/transformation.R

      - name: Commit files
        run: |
          git commit -m "Add regression plot figure"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
